# Generated by Django 3.1.7 on 2021-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('OpCo', models.CharField(max_length=300, null=True)),
                ('EntEmail', models.EmailField(max_length=300, null=True)),
            ],
        ),
    ]
