# Generated by Django 3.1.7 on 2021-03-03 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0002_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('leadid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('project', models.CharField(max_length=500, null=True)),
                ('segment', models.CharField(max_length=100, null=True)),
                ('submitted_by', models.CharField(max_length=100, null=True)),
                ('submitted_to', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('VALIDATED', 'VALIDATED'), ('REJECTED', 'REJECTED')], default='OPEN', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
